{% set name = "bayesian-optimization" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 32e6d5631f0e68d3e76e75b6c44d03269ed38a2fd71e4478370499bdfaa2ddc1

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.8.3, <2.0.0
  run:
    - numpy >=1.25
    - python >={{ python_min }},<4
    - scikit-learn >=1.0.0, <2.0.0
    - scipy >=1.0.0, <2.0.0
    - colorama >=0.4.6, <1.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - bayes_opt

about:
  home: https://github.com/fmfn/BayesianOptimization
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pure Python implementation of bayesian global optimization with gaussian processes.
  doc_url: https://github.com/fmfn/BayesianOptimization
  dev_url: https://github.com/fmfn/BayesianOptimization

extra:
  recipe-maintainers:
    - bwheelz36
    - till-m
    - volpatto
