{% set name = "bayesian-optimization" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d93163709f1861d2343ff66182a4b0cf0ce2d3d2929818becdec7bf78a96acbf

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.9, <4
    - poetry >=1.8.3, <2.0.0
  run:
    - numpy >=1.9.0, <2.0.0
    - python >=3.9, <4
    - scikit-learn >=1.0.0, <2.0.0
    - scipy >=1.0.0, <2.0.0
    - colorama >=0.4.6, <1.0.0

test:
  imports:
    - bayes_opt

about:
  home: https://github.com/fmfn/BayesianOptimization
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pure Python implementation of bayesian global optimization with gaussian processes.
  doc_url: https://github.com/fmfn/BayesianOptimization
  dev_url: https://github.com/fmfn/BayesianOptimization

extra:
  recipe-maintainers:
    - bwheelz36
    - till-m
    - volpatto
