{% set name = "bayesian-optimization" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2fd3af4b6cc24ee1c145295b2a900ffb9b455cad924e8185a8d5784712bc935

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.9.0
    - python
    - scikit-learn >=0.18.0
    - scipy >=0.14.0

test:
  imports:
    - bayes_opt

about:
  home: https://github.com/fmfn/BayesianOptimization
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pure Python implementation of bayesian global optimization with gaussian processes.
  doc_url: https://github.com/fmfn/BayesianOptimization
  dev_url: https://github.com/fmfn/BayesianOptimization

extra:
  recipe-maintainers:
    - volpatto
